/* (c) 2018 KAI OS TECHNOLOGIES (HONG KONG) LIMITED All rights reserved. This
 * file or any portion thereof may not be reproduced or used in any manner
 * whatsoever without the express written permission of KAI OS TECHNOLOGIES
 * (HONG KONG) LIMITED. KaiOS is the trademark of KAI OS TECHNOLOGIES (HONG KONG)
 * LIMITED or its affiliate company and may be registered in some jurisdictions.
 * All other trademarks are the property of their respective owners.
 */

#include "domstubs.idl"

[scriptable, uuid(3a8bf186-0aa1-4f35-be73-cbe17b80851e)]
interface nsIServiceWorkerIPCHelper : nsISupports
{
  /**
  * Brings the app to foreground
  *
  * @param aAppID: the id of the app to be foregrounded
  */
  void sendClientFocusEvent(in unsigned long aAppID);
};

%{ C++
#define NS_SERVICEWORKERIPC_HELPER_CONTRACTID \
  "@mozilla.org/serviceworkers/ipchelper;1"
%}